version: '3.7'

services:
    base_angular:
        container_name: base-angular
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - '.:/var/www'
        ports:
            - '4200:4200'
